function buildMarkdownExport(run) {
  const lines = [];
  lines.push(`# ${run.title || run.topic}`);
  lines.push("");
  lines.push(`**Topic:** ${run.topic}  `);
  lines.push(`**Date:** ${run.createdAt}  `);
  lines.push(`**Model:** ${(run.metadata && run.metadata.model) || "N/A"}  `);
  lines.push(`**Rounds:** ${run.rounds}  `);
  lines.push(`**Status:** ${(run.metadata && run.metadata.status) || "unknown"}  `);

  const usage = run.metadata && run.metadata.tokenUsage;
  if (usage && usage.total_tokens > 0) {
    lines.push(`**Tokens:** ${usage.total_tokens} total (${usage.input_tokens} in / ${usage.output_tokens} out)  `);
  }

  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Discussion Rounds");
  lines.push("");

  for (const round of run.roundMessages || []) {
    lines.push(`### Round ${round.round}: ${round.stage}`);
    if (round.coordinatorPrompt) {
      lines.push(`> Coordinator: ${round.coordinatorPrompt}`);
    }
    lines.push("");

    for (const msg of round.messages || []) {
      lines.push(`#### ${msg.agentName || msg.agentId}`);
      lines.push("");
      lines.push(msg.content || "");
      lines.push("");
    }
  }

  if (run.finalReport) {
    lines.push("---");
    lines.push("");
    lines.push("## Final Report");
    lines.push("");
    lines.push(run.finalReport);
  }

  return lines.join("\n");
}

function buildHtmlExport(run) {
  const title = escHtml(run.title || run.topic);
  const usage = run.metadata && run.metadata.tokenUsage;
  const tokenLine = usage && usage.total_tokens > 0
    ? `<p><strong>Tokens:</strong> ${usage.total_tokens} total (${usage.input_tokens} in / ${usage.output_tokens} out)</p>`
    : "";

  const roundsHtml = (run.roundMessages || [])
    .map((round) => {
      const msgs = (round.messages || [])
        .map((m) => `<div class="msg"><h4>${escHtml(m.agentName || m.agentId)}</h4><pre>${escHtml(m.content || "")}</pre></div>`)
        .join("\n");
      return `<section class="round">
        <h3>Round ${round.round}: ${escHtml(round.stage)}</h3>
        ${round.coordinatorPrompt ? `<p class="coord">Coordinator: ${escHtml(round.coordinatorPrompt)}</p>` : ""}
        ${msgs}
      </section>`;
    })
    .join("\n");

  const finalHtml = run.finalReport
    ? `<hr /><h2>Final Report</h2><pre class="report">${escHtml(run.finalReport)}</pre>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${title} — Scientific Agent Lab</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 900px; margin: 0 auto; padding: 24px; color: #172026; }
  h1 { margin-bottom: 4px; }
  .meta { color: #5a6772; font-size: 0.9rem; margin-bottom: 20px; }
  .meta p { margin: 2px 0; }
  .round { border: 1px solid #d6dde3; border-radius: 8px; padding: 12px; margin-bottom: 12px; }
  .round h3 { margin: 0 0 6px; }
  .coord { color: #5a6772; font-size: 0.88rem; margin: 0 0 10px; }
  .msg { border-left: 4px solid #6b7280; padding: 8px 12px; margin-bottom: 8px; background: #f8fafc; border-radius: 4px; }
  .msg h4 { margin: 0 0 4px; }
  .msg pre, .report { white-space: pre-wrap; font-size: 0.88rem; line-height: 1.4; margin: 0; }
  .report { background: #fefefe; border: 1px solid #d6dde3; border-radius: 8px; padding: 16px; }
  hr { border: 0; border-top: 1px solid #d6dde3; margin: 24px 0; }
  footer { color: #5a6772; font-size: 0.8rem; margin-top: 30px; text-align: center; }
</style>
</head>
<body>
<h1>${title}</h1>
<div class="meta">
  <p><strong>Topic:</strong> ${escHtml(run.topic)}</p>
  <p><strong>Date:</strong> ${run.createdAt}</p>
  <p><strong>Model:</strong> ${escHtml((run.metadata && run.metadata.model) || "N/A")}</p>
  <p><strong>Rounds:</strong> ${run.rounds} | <strong>Status:</strong> ${escHtml((run.metadata && run.metadata.status) || "unknown")}</p>
  ${tokenLine}
</div>
<hr />
<h2>Discussion Rounds</h2>
${roundsHtml}
${finalHtml}
<footer>Generated by Scientific Agent Lab</footer>
</body>
</html>`;
}

function escHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

module.exports = { buildMarkdownExport, buildHtmlExport };
